export const projectsTypes = [
  { value: 'tienda-online', label: 'Tienda online (e‑commerce)' },
  { value: 'blog-personal', label: 'Blog personal' },
  { value: 'blog-tematico', label: 'Blog temático (viajes, gastronomía, tecnología…)' },
  { value: 'portafolio-profesional', label: 'Portafolio profesional (diseñadores, artistas, desarrolladores)' },
  { value: 'pagina-corporativa', label: 'Página corporativa (empresas y pymes)' },
  { value: 'landing-page-producto-campana', label: 'Landing page de producto o campaña' },
  { value: 'marketplace-venta-usuarios', label: 'Marketplace o plataforma de venta entre usuarios' },
  { value: 'sitio-noticias-medios-digitales', label: 'Sitio de noticias y medios digitales' },
  { value: 'plataforma-cursos-online', label: 'Plataforma de cursos online (e‑learning)' },
  { value: 'foro-comunidad-nicho', label: 'Foro o comunidad de nicho' },
  { value: 'sitio-membresia-suscripcion', label: 'Sitio de membresía o suscripción' },
  { value: 'agencia-marketing-diseno', label: 'Agencia de marketing y diseño' },
  { value: 'estudio-arquitectura', label: 'Estudio de arquitectura' },
  { value: 'restaurante-cafeteria-bar', label: 'Restaurante, cafetería o bar' },
  { value: 'consultoria-coaching', label: 'Consultoría y coaching' },
  { value: 'servicio-fotografia-profesional', label: 'Servicio de fotografía profesional' },
  { value: 'salud-bienestar', label: 'Salud y bienestar (clínicas, entrenadores, nutrición)' },
  { value: 'evento-conferencia', label: 'Evento o conferencia' },
  { value: 'inmobiliaria', label: 'Inmobiliaria' },
  { value: 'ong', label: 'Organización sin ánimo de lucro / ONG' },
  { value: 'agencia-viajes-turismo', label: 'Agencia de viajes y turismo' },
  { value: 'podcast-emisora-online', label: 'Podcast o emisora online' },
  { value: 'descarga-saas', label: 'Sitio de descarga o software as a service (SaaS)' },
  { value: 'bolsa-empleo-ofertas', label: 'Bolsa de empleo o agregador de ofertas' },
  { value: 'galeria-arte-exposiciones', label: 'Galería de arte o portfolio de exposiciones' },
  { value: 'recetario-blog-cocina', label: 'Recetario o blog de cocina' },
  { value: 'directorio-local', label: 'Directorio local (negocios, profesionales)' },
  { value: 'plataforma-crowdfunding', label: 'Plataforma de crowdfunding' },
  { value: 'sitio-resenas-recomendaciones', label: 'Sitio de reseñas y recomendaciones' },
  { value: 'consultoria-legal-financiera', label: 'Sitio de consultoría legal o financiera' }
]

export const colorPalettes = [
  { id: 'noche-sereno', name: 'Noche Sereno', primary: '#1b263b', secondary: '#415a77', tertiary: '#778da9', accent: '#e0e1dd', text: '#0d1b2a' },
  { id: 'brisa-marina', name: 'Brisa Marina', primary: '#264653', secondary: '#2a9d8f', tertiary: '#e9c46a', accent: '#f4a261', text: '#ffffff' },
  { id: 'atardecer-vibrante', name: 'Atardecer Vibrante', primary: '#ff6b6b', secondary: '#ffe66d', tertiary: '#4472ca', accent: '#1a535c', text: '#ffffff' },
  { id: 'rosa-urbano', name: 'Rosa Urbano', primary: '#2d132c', secondary: '#541388', tertiary: '#f64c72', accent: '#ffb997', text: '#ffffff' },
  { id: 'costa-azul', name: 'Costa Azul', primary: '#3d5a80', secondary: '#98c1d9', tertiary: '#e0fbfc', accent: '#ee6c4d', text: '#293241' },
  { id: 'sol-radiante', name: 'Sol Radiante', primary: '#ff9f1c', secondary: '#ff4040', tertiary: '#2ec4b6', accent: '#011627', text: '#ffffff' },
  { id: 'bosque-tardio', name: 'Bosque Tardío', primary: '#264653', secondary: '#8ab17d', tertiary: '#faedcd', accent: '#d4a373', text: '#264653' },
  { id: 'purpura-atrevido', name: 'Púrpura Atrevido', primary: '#6a0572', secondary: '#a40e4c', tertiary: '#feb2b2', accent: '#ffee93', text: '#2b2d42' },
  { id: 'noche-electrica', name: 'Noche Eléctrica', primary: '#3a0ca3', secondary: '#560bad', tertiary: '#7209b7', accent: '#b5179e', text: '#ffffff' },
  { id: 'tropical-brillante', name: 'Tropical Brillante', primary: '#06d6a0', secondary: '#1b9aaa', tertiary: '#ef476f', accent: '#ffd166', text: '#073b4c' },
  { id: 'festival-neon', name: 'Festival Neón', primary: '#ffbe0b', secondary: '#fb5607', tertiary: '#ff006e', accent: '#8338ec', text: '#3a86ff' },
  { id: 'despertar-dulce', name: 'Despertar Dulce', primary: '#0081a7', secondary: '#00afb9', tertiary: '#fdfcdc', accent: '#fed9b7', text: '#f07167' },
  { id: 'tech-noir', name: 'Tech Noir', primary: '#2ec4b6', secondary: '#e71d36', tertiary: '#ff9f1c', accent: '#011627', text: '#ffffff' },
  { id: 'crepusculo-pastel', name: 'Crepúsculo Pastel', primary: '#4056a1', secondary: '#6f7bd9', tertiary: '#92acff', accent: '#ffb8b8', text: '#212e59' },
  { id: 'verde-salvaje', name: 'Verde Salvaje', primary: '#007f5f', secondary: '#2b9348', tertiary: '#55a630', accent: '#80b918', text: '#ffffff' },
  { id: 'rosa-suave', name: 'Rosa Suave', primary: '#d8e2dc', secondary: '#ffe5d9', tertiary: '#ffcad4', accent: '#f4acb7', text: '#292524' },
  { id: 'tierra-calida', name: 'Tierra Cálida', primary: '#606c38', secondary: '#dda15e', tertiary: '#fefae0', accent: '#bc6c25', text: '#606c38' },
  { id: 'bosque-silvestre', name: 'Bosque Silvestre', primary: '#354f52', secondary: '#52796f', tertiary: '#84a98c', accent: '#cad2c5', text: '#2f3e46' },
  { id: 'duna-dorada', name: 'Duna Dorada', primary: '#0d3b66', secondary: '#faf0ca', tertiary: '#f4d35e', accent: '#ee964b', text: '#0d3b66' },
  { id: 'galaxia-violeta', name: 'Galaxia Violeta', primary: '#2a0944', secondary: '#0e376b', tertiary: '#4cc9f0', accent: '#f72585', text: '#ffffff' }
];

export const typographyStyles = [
  { id: 'sans-serif', className: 'font-sans', name: 'Sans Serif', description: 'Fuentes sin serifas, perfectas para un diseño moderno y limpio.' },
  { id: 'serif', className: 'font-serif', name: 'Serif', description: 'Fuentes con serifas, ideales para un estilo clásico y elegante.' },
  { id: 'monospace', className: 'font-mono', name: 'Monospace', description: 'Fuentes monoespaciadas, ideales para código y diseño técnico.' },
  { id: 'display', className: 'font-bold tracking-tight', name: 'Display', description: 'Fuentes decorativas, perfectas para títulos y encabezados llamativos.' },
  { id: 'handwritten', className: 'italic', name: 'Handwritten', description: 'Fuentes manuscritas, ideales para un toque personal y creativo.' },
]
